  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  # [[main]]
  # name = "Posts"
  # weight = 200
  # identifier = "posts"
  # url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Blog"
  weight = 450
  identifier = "Blog"
  url = "https://afr0n3rd.blogspot.com/"

  [[main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Wired"
  weight = 510
  identifier = "Wired"
  url = "/Wired/"
  parent = "accomplishments"

  [[main]]
  name = "Wireless"
  weight = 520
  identifier = "Wireless"
  url = "/Wireless/"
  parent = "accomplishments"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
